import { z } from 'zod';
import tuningJson from '@data/tuning.json';

const pair = z.tuple([z.number(), z.number()]);

export const TuningSchema = z.object({
  sim: z.object({ hz: z.number().int().positive(), maxSubSteps: z.number().int().positive() }),
  clock: z.object({
    runSeconds: z.number().positive(),
    heatSeconds: z.number().positive(),
    heatCount: z.number().int().positive(),
    wipeoutPenaltySeconds: z.number().nonnegative(),
    overrunUntilMeterDrains: z.boolean(),
  }),
  wave: z.object({
    curlSpeedFactor: z.number().positive(),
    defaultBreakSpeed: z.number().positive(),
    faceLengthAhead: z.number().positive(),
    faceLengthBehind: z.number().positive(),
    tubeHollownessThreshold: z.number().min(0).max(1),
    sectionWarnSeconds: z.number().nonnegative(),
  }),
  rider: z.object({
    trimSpeed: z.number().positive(),
    maxSpeed: z.number().positive(),
    minStandSpeed: z.number().nonnegative(),
    pumpAccel: z.number().nonnegative(),
    pumpDescendBonus: z.number().nonnegative(),
    climbDrag: z.number().nonnegative(),
    stallDecel: z.number().nonnegative(),
    superStallDecel: z.number().nonnegative(),
    turnRate: z.number().positive(),
    grabTurnRate: z.number().positive(),
    carveTurnRate: z.number().positive(),
    gravityAlongFace: z.number().nonnegative(),
    bogSpeed: z.number().nonnegative(),
    curlCatchMarginU: z.number().nonnegative(),
    proneSpeed: z.number().nonnegative(),
    standWindowV: pair,
    dropSpeedBoost: z.number().nonnegative(),
    carveAccel: z.number().nonnegative(),
    relaxBelowTrim: z.number().nonnegative(),
    relaxAboveTrim: z.number().nonnegative(),
    shoulderStartU: z.number(),
    shoulderEndU: z.number(),
    shoulderSpeedLoss: z.number().min(0).max(1),
    pocketSpeedGain: z.number().nonnegative(),
    proneLiftRate: z.number().nonnegative(),
    proneStandV: z.number().min(0).max(1),
    wipeoutTumbleSeconds: z.number().positive(),
    respawnAheadU: z.number(),
    respawnAheadSeconds: z.number().positive(),
    respawnV: z.number().min(0).max(1),
    boardLength: z.number().positive(),
    headingLevelRate: z.number().nonnegative(),
    /** How far off the line the board will turn before it resists, radians (a cutback goes past 90°). */
    headingMaxRad: z.number().positive(),
    overTheBackSin: z.number().min(0).max(1),
    overTheBackMinSpeed: z.number().nonnegative(),
    stallSpeedFraction: z.number().min(0).max(1),
    superStallSpeedFraction: z.number().min(0).max(1),
    stallRelax: z.number().nonnegative(),
  }),
  /** Dual-stick stance model — see docs/MECHANICS.md. */
  stance: z.object({
    footFollowRate: z.number().positive(),
    railFollowRate: z.number().positive(),
    pumpFullRate: z.number().positive(),
    pumpPhaseDeadzone: z.number().nonnegative(),
    pumpAccelScale: z.number().nonnegative(),
    trimDriveScale: z.number().nonnegative(),
    railCarveBonus: z.number().nonnegative(),
    compressionTurnBonus: z.number().nonnegative(),
    twistTorque: z.number().nonnegative(),
    twistGrip: z.number().nonnegative(),
    twistMaxRad: z.number().positive(),
    twistRecover: z.number().nonnegative(),
    twistSteer: z.number().nonnegative(),
    slideScrub: z.number().nonnegative(),
    slideFailSeconds: z.number().positive(),
    popRate: z.number().positive(),
    loadDecaySeconds: z.number().positive(),
    stallTrim: z.number(),
    tuckSpinBonus: z.number().nonnegative(),
    airTwistScale: z.number().nonnegative(),
    /** Roll rate in the air per unit of rail, rad/s: the flip axis (docs/MECHANICS.md §5). */
    airRollRate: z.number().nonnegative(),
    landAbsorb: z.number().nonnegative(),
    /** Pro mode (assists off) only removes help — see docs/MECHANICS.md §9. */
    proLevelRate: z.number().nonnegative(),
    proTrimDrive: z.number().nonnegative(),
    proLandingWindow: z.number().positive(),
    /** How long a foot shape must hold under a grab button before it is read as that grab. */
    grabSettleSeconds: z.number().nonnegative(),
  }),
  /** Emergent trick recognition thresholds (src/tricks/recognizer.ts). */
  recognizer: z.object({
    engageRail: z.number().positive(),
    releaseRail: z.number().nonnegative(),
    /** How long the rail must stay released before a turn ends; a reversal inside this keeps it going. */
    releaseSeconds: z.number().nonnegative(),
    minGapSeconds: z.number().nonnegative(),
    maxSeconds: z.number().positive(),
    minSwingRad: z.number().nonnegative(),
    minYawRad: z.number().nonnegative(),
    fullSwingRad: z.number().positive(),
    perfectQuality: z.number(),
    lipV: z.number(),
    highV: z.number(),
    bottomV: z.number(),
    slideSeconds: z.number().nonnegative(),
    slideYawRad: z.number().nonnegative(),
    laybackRail: z.number(),
    cutbackSeconds: z.number().nonnegative(),
    worth: z.record(z.string(), z.number()),
  }),
  air: z.object({
    gravity: z.number().positive(),
    launchSpeedScale: z.number().positive(),
    launchLipBonus: z.number().nonnegative(),
    loadMaxSeconds: z.number().positive(),
    loadMinFraction: z.number().min(0).max(1),
    spinRateBase: z.number().nonnegative(),
    spinRateStatScale: z.number().nonnegative(),
    hangTimeStatScale: z.number().nonnegative(),
    perfectWindowDeg: z.number().positive(),
    sloppyWindowDeg: z.number().positive(),
    landingReprojectV: z.number().min(0).max(1),
    launchBase: z.number().nonnegative(),
    launchPerPower: z.number().nonnegative(),
    launchMinV: z.number().min(0).max(1),
    launchMinHeading: z.number(),
    airTimeoutSeconds: z.number().positive(),
    /** Landing windows on the roll residual (degrees from flat), judged alongside the yaw. */
    rollPerfectDeg: z.number().positive(),
    rollSloppyDeg: z.number().positive(),
    landSpeedKeepPerfect: z.number().min(0).max(1.5),
    landSpeedKeepSloppy: z.number().min(0).max(1.5),
  }),
  tube: z.object({
    entrySpeedMax: z.number().positive(),
    minOffsetU: z.number().nonnegative(),
    lengthFactor: z.number().positive(),
    depthRate: z.number().nonnegative(),
    balanceDriftBase: z.number().nonnegative(),
    balanceDriftDepthScale: z.number().nonnegative(),
    balanceDriftTimeScale: z.number().nonnegative(),
    balanceStatScale: z.number().nonnegative(),
    railGrabDriftFactor: z.number().min(0).max(1),
    balanceTapImpulse: z.number().nonnegative(),
    balanceHoldRate: z.number().nonnegative(),
    balanceFailThreshold: z.number().positive(),
    driftFlipMinSeconds: z.number().positive(),
    driftFlipMaxSeconds: z.number().positive(),
    quickCutOffsetU: z.number().nonnegative(),
    quickCutBalanceKick: z.number().nonnegative(),
    depthZones: pair,
    exitSpeed: z.number().positive(),
    escapeAccel: z.number().nonnegative(),
    spitDepth: z.number().min(0).max(1),
  }),
  floater: z.object({
    speedLossPerSecond: z.number().min(0).max(1),
    maxSeconds: z.number().positive(),
    dropSpeedGain: z.number().nonnegative(),
    entryMinV: z.number().min(0).max(1),
  }),
  scoring: z.object({
    base: z.object({
      faceBasic: pair,
      faceSpecial: z.number(),
      grab: z.number(),
      flip: z.number(),
      plainSpin: z.number(),
      airSpecial: pair,
      tubePerSecond: z.number(),
      tubeSquaredPerSecond: z.number(),
      tubeTrick: z.number(),
      tubeSpecial: z.number(),
      floaterPerSecond: z.number(),
      envSecret: pair,
      exitMove: z.number(),
    }),
    repeatDecay: z.array(z.number()).min(1),
    proximityMin: z.number(),
    proximityMax: z.number(),
    proximityBoardLengths: z.number(),
    proximityFarMetres: z.number(),
    rotationPer180: z.number(),
    multiplierCap: z.number().int(),
    perfectBaseFactor: z.number(),
    iconChainBonus: z.number(),
    iconChainCount: z.number().int(),
    idleBankSeconds: z.number().positive(),
  }),
  meter: z.object({
    fill: z.object({
      faceTrick: z.number(),
      grabOrFlip: z.number(),
      special: z.number(),
      tubePerSecond: z.number(),
      floaterPerSecond: z.number(),
    }),
    perfectLanding: z.number(),
    sloppyLanding: z.number(),
    drainPerSecond: z.number(),
    greenDrainPerSecond: z.number(),
    repeatDrain: z.number(),
    wipeoutResetsMeter: z.boolean(),
  }),
  input: z.object({
    sequenceWindowMs: z.number().positive(),
    doubleTapWindowMs: z.number().positive(),
    diagonalConeDeg: z.number().positive(),
    deadzone: z.number().min(0).max(1),
  }),
  stats: z.object({ riderWeight: z.number(), boardWeight: z.number() }),
  camera: z.object({
    chaseDistance: z.number(),
    chaseHeight: z.number(),
    lookAheadU: z.number(),
    lookAheadSpeedScale: z.number(),
    smoothing: z.number(),
    fov: z.number(),
    wideDistance: z.number(),
    wideHeight: z.number(),
    tubeDistance: z.number(),
    tubeHeight: z.number(),
    skateDistance: z.number().positive(),
    skateHeight: z.number(),
    skateBack: z.number(),
    skateSide: z.number(),
    skateFov: z.number().positive(),
    railSwing: z.number().nonnegative(),
    compressionDrop: z.number().nonnegative(),
    speedDolly: z.number().nonnegative(),
    fpEyeHeight: z.number().positive(),
    fpBack: z.number(),
    fpLookDownDeg: z.number(),
    fpFov: z.number().positive(),
  }),
  photo: z.object({ beeps: z.number().int(), beepIntervalSeconds: z.number(), shotsPerRun: z.number().int() }),
  icons: z.object({ stackSize: z.number().int(), dropIntervalSeconds: z.number() }),
  replay: z.object({ leadSeconds: z.number(), tailSeconds: z.number(), maxSeconds: z.number() }),
});

export type Tuning = z.infer<typeof TuningSchema>;

export function parseTuning(raw: unknown): Tuning {
  return TuningSchema.parse(raw);
}

/** The single shared tuning object. Mutable on purpose so a debug panel can live-tune. */
export const TUNING: Tuning = parseTuning(tuningJson);
